import type { TemplateDefinition } from '../types/template'

export const blogCover: TemplateDefinition = {
  id: 'blog-cover',
  name: 'Template 8',
  description: 'Wide format blog header with connected nodes',
  category: 'brand-gradient',
  defaults: {
    headline: 'Building Better\nAI Memory',
    subtitle: 'The Architecture Behind MemSync',
    headlineFontFamily: 'Geist',
    headlineFontSize: 72,
    headlineFontWeight: 800,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 24,
    subtitleFontWeight: 400,
    subtitleColor: '#E9F8FC',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-soft',
    gradientColors: ['#167188', '#50C9E9', '#BDEBF7', '#FFFFFF'],
    gradientAngle: 180,
    solidColor: '#167188',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: true, opacity: 0.25, nodeCount: 15, color: '#FFFFFF' },
      glow: { enabled: false, opacity: 0.3, color: '#24BCE3', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-left',
    logoScale: 1.0,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
