import type { TemplateDefinition } from '../types/template'

export const brandGradientHero: TemplateDefinition = {
  id: 'brand-gradient-hero',
  name: 'Brand Gradient Hero',
  description: 'Large centered headline on brand teal gradient',
  category: 'brand-gradient',
  defaults: {
    headline: 'The Network for\nOpen Intelligence',
    subtitle: 'Powering the next generation of verifiable AI',
    headlineFontFamily: 'Inter',
    headlineFontSize: 72,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 24,
    subtitleFontWeight: 400,
    subtitleColor: '#FFFFFF',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-vertical',
    gradientColors: ['#0E4B5B', '#24BCE3', '#E9F8FC'],
    gradientAngle: 180,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-center',
    logoScale: 0.7,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
