import type { TemplateDefinition } from '../types/template'

export const communitySpotlight: TemplateDefinition = {
  id: 'community-spotlight',
  name: 'Weekly Yappers',
  description: 'Multi-section community highlights with PFP grid',
  category: 'dark-technical',
  defaults: {
    headline: 'Weekly Yapper Highlights',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 56,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'top',
    textPaddingX: 60,
    textPaddingY: 20,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-gradient-teal',
    gradientColors: ['#0E4B5B', '#041317'],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'top-right',
    logoScale: 0.6,
    logoPadding: 30,
    communityEnabled: true,
    communitySections: [
      {
        title: 'Top Yappers',
        members: [
          { imageUrl: null, username: '@member1' },
          { imageUrl: null, username: '@member2' },
          { imageUrl: null, username: '@member3' },
          { imageUrl: null, username: '@member4' },
          { imageUrl: null, username: '@member5' },
          { imageUrl: null, username: '@member6' },
          { imageUrl: null, username: '@member7' },
          { imageUrl: null, username: '@member8' },
        ],
      },
      {
        title: 'Best Art',
        members: [
          { imageUrl: null, username: '@artist1' },
          { imageUrl: null, username: '@artist2' },
          { imageUrl: null, username: '@artist3' },
        ],
      },
      {
        title: 'Top Educator',
        members: [
          { imageUrl: null, username: '@educator1' },
          { imageUrl: null, username: '@educator2' },
          { imageUrl: null, username: '@educator3' },
        ],
      },
    ],
    communityAvatarSize: 90,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 22,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 13,
    communityColumnsPerRow: 4,
  },
}
