import type { TemplateDefinition } from '../types/template'

export const communityAward: TemplateDefinition = {
  id: 'community-award',
  name: 'Template 15',
  description: 'Spotlight 4 community members with large avatars',
  category: 'dark-technical',
  defaults: {
    headline: 'Best Community Members',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 52,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'center',
    textVerticalPosition: 'top',
    textPaddingX: 80,
    textPaddingY: 20,
    backgroundType: 'solid',
    backgroundPresetId: 'dark-deepest',
    gradientColors: [],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: true, opacity: 0.25, density: 50, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.08, count: 12, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.4, color: '#0E4B5B', x: 50, y: 60 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'bottom-center',
    logoScale: 1.0,
    logoPadding: 30,
    communityEnabled: true,
    communitySections: [
      {
        title: 'Hall of Fame',
        members: [
          { imageUrl: null, username: '@member1' },
          { imageUrl: null, username: '@member2' },
          { imageUrl: null, username: '@member3' },
          { imageUrl: null, username: '@member4' },
        ],
      },
    ],
    communityAvatarSize: 120,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 4,
    communitySectionTitleColor: '#40D1DB',
    communitySectionTitleSize: 22,
    communityUsernameColor: '#FFFFFF',
    communityUsernameSize: 16,
    communityColumnsPerRow: 4,
  },
}
