import type { TemplateDefinition } from '../types/template'

export const communitySpotlight: TemplateDefinition = {
  id: 'community-spotlight',
  name: 'Template 13',
  description: 'Multi-section community highlights with PFP grid',
  category: 'dark-technical',
  defaults: {
    headline: 'Weekly Top Contributors\nHighlights',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 56,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'top',
    textPaddingX: 60,
    textPaddingY: 20,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-gradient-teal',
    gradientColors: ['#0E4B5B', '#041317'],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
      isometricGrid: { enabled: false, opacity: 0.3, color: '#40D1DB' },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'top-right',
    logoScale: 1.0,
    logoPadding: 30,
    communityEnabled: true,
    communitySections: [
      {
        title: 'New OGs',
        members: [
          { imageUrl: null, username: '@member1' },
          { imageUrl: null, username: '@member2' },
          { imageUrl: null, username: '@member3' },
          { imageUrl: null, username: '@member4' },
          { imageUrl: null, username: '@member5' },
          { imageUrl: null, username: '@member6' },
          { imageUrl: null, username: '@member7' },
          { imageUrl: null, username: '@member8' },
        ],
      },
      {
        title: 'Most Active OG',
        members: [
          { imageUrl: null, username: '@educator1' },
          { imageUrl: null, username: '@educator2' },
          { imageUrl: null, username: '@educator3' },
          { imageUrl: null, username: '@educator4' },
          { imageUrl: null, username: '@educator5' },
          { imageUrl: null, username: '@educator6' },
          { imageUrl: null, username: '@educator7' },
          { imageUrl: null, username: '@educator8' },
        ],
      },
    ],
    communityAvatarSize: 90,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 22,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 13,
    communityColumnsPerRow: 4,
    imageEnabled: false,
    imageSrc: null,
    imageX: 50,
    imageY: 50,
    imageScale: 0.5,
    imageOpacity: 1,
  },
}
