import type { TemplateDefinition } from '../types/template'

export const communityTopContributor: TemplateDefinition = {
  id: 'community-top-contributor',
  name: 'Template 14',
  description: 'Highlight 8 community members in a clean grid',
  category: 'brand-gradient',
  defaults: {
    headline: 'Top Contributors',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 52,
    headlineFontWeight: 800,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#E9F8FC',
    textAlignment: 'center',
    textVerticalPosition: 'top',
    textPaddingX: 80,
    textPaddingY: 20,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-vertical',
    gradientColors: ['#0E4B5B', '#1D96B6', '#24BCE3'],
    gradientAngle: 180,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
      isometricGrid: { enabled: false, opacity: 0.3, color: '#40D1DB' },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'bottom-center',
    logoScale: 2.0,
    logoPadding: 30,
    communityEnabled: true,
    communitySections: [
      {
        title: 'This Week',
        members: [
          { imageUrl: null, username: '@member1' },
          { imageUrl: null, username: '@member2' },
          { imageUrl: null, username: '@member3' },
          { imageUrl: null, username: '@member4' },
          { imageUrl: null, username: '@member5' },
          { imageUrl: null, username: '@member6' },
          { imageUrl: null, username: '@member7' },
          { imageUrl: null, username: '@member8' },
        ],
      },
    ],
    communityAvatarSize: 100,
    communityAvatarBorderColor: '#FFFFFF',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 24,
    communityUsernameColor: '#FFFFFF',
    communityUsernameSize: 15,
    communityColumnsPerRow: 4,
    imageEnabled: false,
    imageSrc: null,
    imageX: 50,
    imageY: 50,
    imageScale: 0.5,
    imageOpacity: 1,
  },
}
