import type { TemplateDefinition } from '../types/template'

export const darkTechFeature: TemplateDefinition = {
  id: 'dark-tech-feature',
  name: 'Template 4',
  description: 'Feature highlight with geometric cubes on dark background',
  category: 'dark-technical',
  defaults: {
    headline: 'Proof of Intelligence:\nVerifiability',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 64,
    headlineFontWeight: 600,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 22,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-teal-glow',
    gradientColors: ['#0E4B5B', '#0A0F19'],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: true, opacity: 0.3, count: 8, color: '#40D1DB' },
      radialLines: { enabled: true, opacity: 0.15, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.4, color: '#0E4B5B', x: 50, y: 60 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'top-left',
    logoScale: 1.0,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
