import type { TemplateDefinition } from '../types/template'

export const darkTechStatement: TemplateDefinition = {
  id: 'dark-tech-statement',
  name: 'Template 5',
  description: 'Bold two-line statement on dark teal gradient',
  category: 'dark-technical',
  defaults: {
    headline: 'Private data.\nPublic proof.',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 80,
    headlineFontWeight: 500,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-gradient-teal',
    gradientColors: ['#0E4B5B', '#041317'],
    gradientAngle: 180,
    solidColor: '#041317',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: true, opacity: 0.12, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.3, color: '#0E4B5B', x: 70, y: 50 },
      isometricGrid: { enabled: false, opacity: 0.3, color: '#40D1DB' },
    },
    logoEnabled: true,
    logoVariant: 'symbol',
    logoColor: 'cyan',
    logoPosition: 'top-left',
    logoScale: 1.5,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
    imageEnabled: false,
    imageSrc: null,
    imageX: 50,
    imageY: 50,
    imageScale: 0.5,
    imageOpacity: 1,
  },
}
