import type { TemplateDefinition } from '../types/template'

export const editorialStatement: TemplateDefinition = {
  id: 'editorial-statement',
  name: 'Editorial Statement',
  description: 'Bold magazine-style editorial layout',
  category: 'dark-technical',
  defaults: {
    headline: 'The future of AI\nis verifiable.',
    subtitle: 'A new paradigm for trust in machine intelligence',
    headlineFontFamily: 'Geist',
    headlineFontSize: 68,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 20,
    subtitleFontWeight: 300,
    subtitleColor: '#BDEBF7',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 100,
    textPaddingY: 80,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-gradient-vertical',
    gradientColors: ['#141E32', '#0A0F19'],
    gradientAngle: 180,
    solidColor: '#141E32',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.06, count: 20, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.15, color: '#0E4B5B', x: 0, y: 100 },
    },
    logoEnabled: true,
    logoVariant: 'logotype',
    logoColor: 'cyan',
    logoPosition: 'top-left',
    logoScale: 0.6,
    logoPadding: 50,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
