import type { TemplateDefinition } from '../types/template'

export const hiringPost: TemplateDefinition = {
  id: 'hiring-post',
  name: 'Template 12',
  description: 'Recruitment card for open positions',
  category: 'brand-gradient',
  defaults: {
    headline: "We're Hiring!",
    subtitle: 'Senior AI Engineer\nJoin us in building open, verifiable AI infrastructure',
    headlineFontFamily: 'Geist',
    headlineFontSize: 72,
    headlineFontWeight: 800,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 24,
    subtitleFontWeight: 400,
    subtitleColor: '#E9F8FC',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-diagonal',
    gradientColors: ['#0E4B5B', '#167188', '#1D96B6', '#24BCE3'],
    gradientAngle: 135,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: true, opacity: 0.2, nodeCount: 10, color: '#FFFFFF' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
      isometricGrid: { enabled: false, opacity: 0.3, color: '#40D1DB' },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-center',
    logoScale: 1.0,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
    imageEnabled: false,
    imageSrc: null,
    imageX: 50,
    imageY: 50,
    imageScale: 0.5,
    imageOpacity: 1,
  },
}
