import type { TemplateDefinition } from '../types/template'

export const minimalClean: TemplateDefinition = {
  id: 'minimal-clean',
  name: 'Minimal Clean',
  description: 'Ultra-clean typography with generous whitespace',
  category: 'brand-gradient',
  defaults: {
    headline: 'Less noise.\nMore signal.',
    subtitle: 'OpenGradient',
    headlineFontFamily: 'Geist',
    headlineFontSize: 64,
    headlineFontWeight: 600,
    headlineColor: '#0E4B5B',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 18,
    subtitleFontWeight: 500,
    subtitleColor: '#167188',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 120,
    textPaddingY: 80,
    backgroundType: 'solid',
    backgroundPresetId: 'brand-gradient-soft',
    gradientColors: ['#BDEBF7', '#FFFFFF'],
    gradientAngle: 180,
    solidColor: '#FFFFFF',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'symbol',
    logoColor: 'cyan',
    logoPosition: 'bottom-center',
    logoScale: 0.5,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
