import type { TemplateDefinition } from '../types/template'

export const modelHubChart: TemplateDefinition = {
  id: 'model-hub-chart',
  name: 'Template 16',
  description: 'Branded chart graphic with gradient background, title top-left, logo top-right',
  category: 'brand-gradient',
  defaults: {
    headline: 'Distribution of Log Returns',
    subtitle: '',
    headlineFontFamily: 'Geist',
    headlineFontSize: 48,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist',
    subtitleFontSize: 18,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'top',
    textPaddingX: 60,
    textPaddingY: 40,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-vertical',
    gradientColors: ['#0E4B5B', '#1D96B6', '#24BCE3'],
    gradientAngle: 180,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
      isometricGrid: { enabled: false, opacity: 0.3, color: '#40D1DB' },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-right',
    logoScale: 0.8,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
    imageEnabled: true,
    imageSrc: null,
    imageX: 50,
    imageY: 55,
    imageScale: 0.85,
    imageOpacity: 1,
  },
}
