import type { TemplateDefinition } from '../types/template'

export const socialQuote: TemplateDefinition = {
  id: 'social-quote',
  name: 'Quote Card',
  description: 'Quote-style card with subtle dark background',
  category: 'dark-technical',
  defaults: {
    headline: 'AI should be open,\nverifiable, and\npermissionless.',
    subtitle: '— OpenGradient',
    headlineFontFamily: 'Playfair Display',
    headlineFontSize: 56,
    headlineFontWeight: 500,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 20,
    subtitleFontWeight: 500,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 80,
    backgroundType: 'solid',
    backgroundPresetId: 'dark-navy',
    gradientColors: [],
    gradientAngle: 180,
    solidColor: '#141E32',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.08, count: 15, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.2, color: '#0E4B5B', x: 30, y: 70 },
    },
    logoEnabled: true,
    logoVariant: 'symbol',
    logoColor: 'cyan',
    logoPosition: 'bottom-right',
    logoScale: 0.5,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
