import type { TemplateDefinition } from '../types/template'

export const threadCloser: TemplateDefinition = {
  id: 'thread-closer',
  name: 'Template 7',
  description: 'End of thread slide with logo watermark',
  category: 'dark-technical',
  defaults: {
    headline: 'End of thread.',
    subtitle: 'THANKS FOR READING',
    headlineFontFamily: 'Geist',
    headlineFontSize: 80,
    headlineFontWeight: 500,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Geist Mono',
    subtitleFontSize: 16,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'solid',
    backgroundPresetId: 'dark-deepest',
    gradientColors: [],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.1, count: 20, color: '#141E32' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.3, color: '#0E4B5B', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-center',
    logoScale: 1.0,
    logoPadding: 40,
    communityEnabled: false,
    communitySections: [],
    communityAvatarSize: 80,
    communityAvatarBorderColor: '#40D1DB',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 20,
    communityUsernameColor: '#A7E4F4',
    communityUsernameSize: 14,
    communityColumnsPerRow: 4,
  },
}
