import type { TemplateDefinition } from '../types/template'

export const brandGradientSplit: TemplateDefinition = {
  id: 'brand-gradient-split',
  name: 'Brand Gradient Split',
  description: 'Left-aligned text on diagonal brand gradient',
  category: 'brand-gradient',
  defaults: {
    headline: 'Building the Future\nof Open AI',
    subtitle: 'Decentralized, verifiable, and permissionless',
    headlineFontFamily: 'Inter',
    headlineFontSize: 64,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 22,
    subtitleFontWeight: 400,
    subtitleColor: '#E9F8FC',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-diagonal',
    gradientColors: ['#0E4B5B', '#167188', '#A7E4F4', '#E9F8FC'],
    gradientAngle: 135,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.3, color: '#24BCE3', x: 70, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-left',
    logoScale: 0.6,
    logoPadding: 40,
  },
}
