import type { TemplateDefinition } from '../types/template'

export const communityTopContributor: TemplateDefinition = {
  id: 'community-top-contributor',
  name: 'Top Contributor',
  description: 'Celebrate a top community contributor',
  category: 'brand-gradient',
  defaults: {
    headline: 'Top Contributor\nof the Month',
    subtitle: 'Alex Kim  |  42 PRs merged  |  156 community helps\nThank you for making OpenGradient better',
    headlineFontFamily: 'Montserrat',
    headlineFontSize: 60,
    headlineFontWeight: 800,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#E9F8FC',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-vertical',
    gradientColors: ['#0E4B5B', '#24BCE3', '#E9F8FC'],
    gradientAngle: 180,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: true, opacity: 0.25, density: 50, color: '#FFFFFF' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: true, opacity: 0.15, nodeCount: 8, color: '#FFFFFF' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-center',
    logoScale: 0.6,
    logoPadding: 35,
  },
}
