import type { TemplateDefinition } from '../types/template'

export const communitySpotlight: TemplateDefinition = {
  id: 'community-spotlight',
  name: 'Community Spotlight',
  description: 'Featured community member highlight',
  category: 'dark-technical',
  defaults: {
    headline: 'Community Spotlight',
    subtitle: '@vitalik_eth\nTop contributor to OpenGradient governance proposals this quarter',
    headlineFontFamily: 'Space Grotesk',
    headlineFontSize: 48,
    headlineFontWeight: 700,
    headlineColor: '#40D1DB',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 24,
    subtitleFontWeight: 400,
    subtitleColor: '#FFFFFF',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 80,
    backgroundType: 'solid',
    backgroundPresetId: 'dark-deepest',
    gradientColors: [],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: true, opacity: 0.3, density: 45, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.1, count: 10, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.35, color: '#0E4B5B', x: 20, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'top-left',
    logoScale: 0.5,
    logoPadding: 40,
  },
}
