import type { TemplateDefinition } from '../types/template'

export const communityAward: TemplateDefinition = {
  id: 'community-award',
  name: 'Community Award',
  description: 'Award-style card for outstanding community members',
  category: 'dark-technical',
  defaults: {
    headline: 'Best Community\nMember 2026',
    subtitle: 'Awarded to @username\nFor exceptional contributions to the OpenGradient ecosystem',
    headlineFontFamily: 'Orbitron',
    headlineFontSize: 52,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 22,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 80,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-gradient-teal',
    gradientColors: ['#0E4B5B', '#041317'],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: true, opacity: 0.4, density: 70, color: '#40D1DB' },
      cubes: { enabled: true, opacity: 0.15, count: 4, color: '#40D1DB' },
      radialLines: { enabled: true, opacity: 0.12, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.5, color: '#0E4B5B', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'symbol',
    logoColor: 'cyan',
    logoPosition: 'top-center',
    logoScale: 0.8,
    logoPadding: 35,
  },
}
