import type { TemplateDefinition } from '../types/template'

export const communityTopContributor: TemplateDefinition = {
  id: 'community-top-contributor',
  name: 'Top 6 Members',
  description: 'Highlight 6 community members in a clean grid',
  category: 'brand-gradient',
  defaults: {
    headline: 'Top Contributors',
    subtitle: '',
    headlineFontFamily: 'Montserrat',
    headlineFontSize: 52,
    headlineFontWeight: 800,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#E9F8FC',
    textAlignment: 'center',
    textVerticalPosition: 'top',
    textPaddingX: 80,
    textPaddingY: 20,
    backgroundType: 'gradient',
    backgroundPresetId: 'brand-gradient-vertical',
    gradientColors: ['#0E4B5B', '#24BCE3', '#E9F8FC'],
    gradientAngle: 180,
    solidColor: '#0E4B5B',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.4, color: '#24BCE3', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-center',
    logoScale: 0.6,
    logoPadding: 25,
    communityEnabled: true,
    communitySections: [
      {
        title: 'This Week',
        members: [
          { imageUrl: null, username: '@member1' },
          { imageUrl: null, username: '@member2' },
          { imageUrl: null, username: '@member3' },
          { imageUrl: null, username: '@member4' },
          { imageUrl: null, username: '@member5' },
          { imageUrl: null, username: '@member6' },
        ],
      },
    ],
    communityAvatarSize: 100,
    communityAvatarBorderColor: '#FFFFFF',
    communityAvatarBorderWidth: 3,
    communitySectionTitleColor: '#FFFFFF',
    communitySectionTitleSize: 24,
    communityUsernameColor: '#E9F8FC',
    communityUsernameSize: 15,
    communityColumnsPerRow: 3,
  },
}
