import type { TemplateDefinition } from '../types/template'

export const darkTechStatement: TemplateDefinition = {
  id: 'dark-tech-statement',
  name: 'Dark Statement',
  description: 'Bold two-line statement on dark teal gradient',
  category: 'dark-technical',
  defaults: {
    headline: 'Private data.\nPublic proof.',
    subtitle: '',
    headlineFontFamily: 'Playfair Display',
    headlineFontSize: 80,
    headlineFontWeight: 500,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 20,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-gradient-teal',
    gradientColors: ['#0E4B5B', '#041317'],
    gradientAngle: 180,
    solidColor: '#041317',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: true, opacity: 0.12, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.3, color: '#0E4B5B', x: 70, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'symbol',
    logoColor: 'cyan',
    logoPosition: 'top-left',
    logoScale: 0.6,
    logoPadding: 40,
  },
}
