import type { TemplateDefinition } from '../types/template'

export const darkTechAnnouncement: TemplateDefinition = {
  id: 'dark-tech-announcement',
  name: 'Dark Announcement',
  description: 'Centered text on dark background with particle field',
  category: 'dark-technical',
  defaults: {
    headline: 'Introducing PIPE',
    subtitle: 'Parallel Inference Pre-Execution Engine',
    headlineFontFamily: 'Playfair Display',
    headlineFontSize: 80,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 24,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'solid',
    backgroundPresetId: 'dark-deepest',
    gradientColors: [],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: true, opacity: 0.5, density: 60, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.15, count: 12, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.5, color: '#0E4B5B', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'top-center',
    logoScale: 0.6,
    logoPadding: 40,
  },
}
