import type { TemplateDefinition } from '../types/template'

export const teamSpotlight: TemplateDefinition = {
  id: 'team-spotlight',
  name: 'Team Spotlight',
  description: 'Highlight a team member with name and role',
  category: 'dark-technical',
  defaults: {
    headline: 'Meet Sarah Chen',
    subtitle: 'Head of AI Research\nBuilding the future of verifiable inference at OpenGradient',
    headlineFontFamily: 'Sora',
    headlineFontSize: 56,
    headlineFontWeight: 700,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Inter',
    subtitleFontSize: 22,
    subtitleFontWeight: 400,
    subtitleColor: '#A7E4F4',
    textAlignment: 'left',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 80,
    backgroundType: 'gradient',
    backgroundPresetId: 'dark-teal-glow',
    gradientColors: ['#0E4B5B', '#0A0F19'],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: true, opacity: 0.2, density: 30, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: false, opacity: 0.3, count: 8, color: '#24BCE3' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: true, opacity: 0.4, color: '#0E4B5B', x: 80, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'cyan',
    logoPosition: 'top-left',
    logoScale: 0.5,
    logoPadding: 40,
  },
}
