import type { TemplateDefinition } from '../types/template'

export const threadCloser: TemplateDefinition = {
  id: 'thread-closer',
  name: 'Thread Closer',
  description: 'End of thread slide with logo watermark',
  category: 'dark-technical',
  defaults: {
    headline: 'End of thread.',
    subtitle: 'THANKS FOR READING',
    headlineFontFamily: 'Playfair Display',
    headlineFontSize: 80,
    headlineFontWeight: 500,
    headlineColor: '#FFFFFF',
    subtitleFontFamily: 'Space Mono',
    subtitleFontSize: 16,
    subtitleFontWeight: 400,
    subtitleColor: '#6A7282',
    textAlignment: 'center',
    textVerticalPosition: 'center',
    textPaddingX: 80,
    textPaddingY: 60,
    backgroundType: 'solid',
    backgroundPresetId: 'dark-deepest',
    gradientColors: [],
    gradientAngle: 180,
    solidColor: '#0A0F19',
    decorations: {
      particles: { enabled: false, opacity: 0.3, density: 40, color: '#40D1DB' },
      cubes: { enabled: false, opacity: 0.3, count: 5, color: '#40D1DB' },
      radialLines: { enabled: false, opacity: 0.2, color: '#24BCE3' },
      streaks: { enabled: true, opacity: 0.1, count: 20, color: '#1D2C4B' },
      nodes: { enabled: false, opacity: 0.3, nodeCount: 12, color: '#40D1DB' },
      glow: { enabled: false, opacity: 0.3, color: '#0E4B5B', x: 50, y: 50 },
    },
    logoEnabled: true,
    logoVariant: 'lockup-horizontal',
    logoColor: 'white',
    logoPosition: 'top-center',
    logoScale: 0.5,
    logoPadding: 40,
  },
}
